name: Develop release flow

on:
  push:
    branches:
      - develop

jobs:
  build-project:
    name: Build and release application
    runs-on: windows-2016
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instal YARN dependencies
        run: yarn install

      - name: Build project for windows
        run: yarn build:win

      - name: Zip the files
        uses: papeloto/action-zip@v1
        with:
          files: dist/win-ia32-unpacked
          dest: connect-marketing-develop.zip

      - name: Release project files to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.run_number}}
          name: Release v.1.0.${{github.run_number}}
          files: connect-marketing-develop.zip
